### ISSUE TITLE
`assignment-02` selling web

### ISSUE THREAD

**Issue by seunguri** [LikeLion-at-CAU-10th/Jinu-Kim#2]
다양한 css 속성들을 이용해서 수요일 세션에서 만들었던 자기소개 페이지보다 훨씬 좋네요! 특히 flex 이용한 거 보고 놀랐어요. 직접 찾아보고 적용한 건가요?
css 컴포넌트 작명도 직관적으로 너무 잘했어요. product, product_name ...
커피머신은 품절인 소소한 디테일도 재밌어요👍

추가로 드리고 싶은 피드백은 두 가지예요.
**1. margin 이외의 다양한 Box Model 활용하기**
**2. 중복되는 CSS 컴포넌트는 묶어서 클린하게 코드짜기**
coffe.css와 candle.css는 하나로 합칠 수 있어요. sellling.css에서는 product라고 칭했으니 product.css도 괜찮아보입니다.
nav, ul, body, footer는 동일하고 s와 overall , state와 price는 이름과 의미는 다르지만 사실 같은 역할을 하고 있어요. 
아래와 같이 합치는 방안을 추천해요.
```css
nav{
    background-color:rgb(196, 235, 125);
    width: auto;
    height: 20px;
}
ul{
    display: flex;
    justify-content: space-around;
}
body{
    background-color: bisque;
}

#s와 overall을 포괄하는 이름{
    text-align: center;
    display: block;
    margin-top: 50px;
}

#price와 state를 포괄하는 이름{
    color:red;
}

footer{
    display: block;
    text-align: center;
    margin-top: 60px;
}
```
