### ISSUE TITLE
`2nd_assignment`

### ISSUE THREAD

**Issue by seunguri** [LikeLion-at-CAU-10th/Jinu-Kim#3]
![image](https://user-images.githubusercontent.com/52988414/161803990-410ae088-a56e-4c3d-bc9c-75829b9f71e2.png)
인더스트리얼시큐리티 😎
css 디테일이 장난아니군요. groove라는 border 속성도 찰떡이에요.

무엇보다 contact에서 공통적인 부분은 묶고 1, 2로 나눠준 코드보고 감동받았어요. 
역시 에이스입니다!
```css
.contact{
    background-color: rgb(248, 172, 58);
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    justify-content: center;
    align-items: center;
    border: ridge 10px;
    border-color: rgb(245, 163, 10);
}
.contact1{
    flex-basis: 25%;
}
.contact2{
    flex-basis: 60%;
}
```
